on:
  release:
    types: [created]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Release Binaries
        run: cargo build --release

      - name: Add artifacts to GH release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/uattool.exe
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}